### PR TITLE
Pipe through logs from the spawned openapi generator process

### PR DESCRIPTION
**Pull request by youngchen7**
Log the command and arguments passed to `openapi-generator-cli`

Add a handler to stdout for the spawned child process, and log data using the nx devkit logger.

Add `silent` option to suppress output

docs: add joeflateau as a contributor for doc

### CODE REVIEW

**Comment by trumbitta** [comment]
👋 Hey @youngchen7,
🚀 Thank you! This is an awesome contribution!

🙏 Before I take it for a spin, and most certainly merge it, would you mind also adding relevant test cases to the unit tests for the executor?

**Comment by youngchen7** [comment]
Yup, I'll look into adding unit tests either today or tomorrow!

**Comment by youngchen7** [comment]
I've added the unit tests. It's a little odd to mock / expect from a logger, but I didn't see another good way to validate that the output was being forwarded.

Originally I wanted to add a unit test that would validate the fix for the child buffer size causing process hangs, but that's a spawn implementation specific issue and not possible to test, I think.

**Comment by trumbitta** [comment]
closing in favor of #72!

**Pull request closed without merging**
