### PR TITLE
Fixes Issue With Generating Sources on Windows

### LINKED ISSUE #21: Running Target Failed for Both Client Sources & Docs
I'm unable to get this to work on Windows, even using just the sample spec.

# Environment
* nx-plugin-api: 1.3.0
* Node: 14.16.1
* npm: 6.14.2
* Nx: 12.3.4
* OS: Windows 10 Enterprise

# Output

```
⚡ DanielBreen@DBREENBC  C:\..\..\app   master ≢ +3 ~5 -0 ! nx generate @trumbitta/nx-plugin-openapi:api-spec
√ What name would you like to use? · test-spec
√ Do you want me to also create a sample spec file for you? (y/N) · true

UPDATE angular.json
UPDATE nx.json
CREATE libs/test-spec/src/test-spec.openapi.yml
⚡ DanielBreen@DBREENBC  C:\..\..\app   master ≢ +4 ~5 -0 ! nx generate @trumbitta/nx-plugin-openapi:api-lib
√ What name would you like to use? · test-lib
√ Which OpenAPITool generator would you like to use? (https://github.com/OpenAPITools/openapi-generator) · typescript-fetch
√ Is the API spec file published online? (y/N) · false
√ If it's online, what's the URL where I can get the API spec file from? · 
√ If it's online, which authorization headers do you need to add? ·
√ If it's local, what's the name of the lib containing the API spec file? · test-spec
√ If it's local, what's the path of the API spec file starting from the lib root? · src/test-spec.openapi.yml
√ Do you want to specify any additional properties for the generator? key1=value1,key2=value2 (https://openapi-generator.tech/docs/generators) · 
UPDATE angular.json
UPDATE nx.json
CREATE libs/test-lib/README.md
UPDATE tsconfig.base.json     
⚡ DanielBreen@DBREENBC  C:\..\..\app   master ≢ +5 ~5 -0 ! nx run test-lib:generate-sources   

> nx run test-lib:generate-sources 
Deleting outputDir libs/test-lib/src...
Done deleting outputDir libs/test-lib/src.

———————————————————————————————————————————————

>  NX   ERROR  Running target "test-lib:generate-sources" failed

  Failed tasks:

  - test-lib:generate-sources
```

_Updated 5-26-2021: Include environment details_

### PR DESCRIPTION
**Pull request by djbreen7**
Fixes #21

### CODE REVIEW

**Comment by djbreen7** [comment]
@trumbitta Definitely let me know if there's something else I need to do. I wasn't able to figure out how to run the tests. I enabled `esModuleInterop` for `import spawn from 'cross-spawn';` to work. I also wouldn't be surprised if you don't like the choice I made to install a dependency.

In summary, there's an issue using `childProcess.spawn` in windows. Some workaround suggest specifying the command extension and passing `{shell: true}`, but I didn't have any luck with that. More explanation [here](https://www.npmjs.com/package/cross-spawn#why)

e.g, `spawn('node_modules/.bin/openapi-generator-cli.cmd', args, {shell: true});`

**Comment by trumbitta** [comment]
Thank you @djbreen7 , I read the explanations and I'm fine with the new dependency!

I also tried your PR myself and I'd like to ask you for two little changes:

1. Moving the `esModuleInterop` from `tsconfig.base.json` to `packages/nx-plugin-openapi/tsconfig.lib.json`  
It's a useful option, but I'd like to keep it where it's needed for now.
1. Also installing, as a dev dependency, the types for `cross-spawn`  
```sh
# here's the command for your copy-pasting convenience :D 
npm i -D @types/cross-spawn
```

After these two changes, I'll happily merge the PR and release a new version ASAP :shipit: 

P.S.: you can run the e2e tests with  
```sh
nx e2e nx-plugin-openapi-e2e
```
This will create a new Nx workspace in `tmp/nx-e2e/proj/` and execute some commands to check that the plugin works.

I realize now I need to work on #25 😄

**Comment by djbreen7** [comment]
@trumbitta Sounds good. I'll quickly make those changes on Tuesday.

**Comment by djbreen7** [comment]
@trumbitta Had some time this morning. All set!

**Comment by trumbitta** [comment]
👍 I merged the commits from this via #27 (the only difference being a new commit I made to use a named import) because it worked on my machine but not on Github Actions 🤷 

Anyway, going to release to npm!

**Pull request merged**
