### PR TITLE
feat(global-properties): add global-properties option

### PR DESCRIPTION
**Pull request by djbreen7**
Adding feature as described here: https://openapi-generator.tech/docs/globals#note-on-global-property-declaration

### CODE REVIEW

**Comment by djbreen7** [comment]
Will resolve conflicts ASAP

**Comment by djbreen7** [comment]
@trumbitta I _think_ this is ready to go. I see that the executor tests are disabled. This didn't actually work when I tried it with `npm link`. I'm hoping it's a fluke, but definitely raises some flags.

How do you normally test your changes? Doing my best to make my PRs as hands-free for you as possible.

**Comment by trumbitta** [comment]
@djbreen7 I just published v1.4.0 with this feature! :shipit: 
🥳 🎉 🚀 Thank you so much for your contributions and debugging!

As you'll see, this PR didn't work because it was missing a bit (see #29, you'll find your commits then my own with the addition).

About testing: I basically do this https://nx.dev/latest/angular/nx-plugin/overview#testing-your-plugin but the fun part is that

> When the E2E app runs, a temporary E2E directory is created in the root of the workspace. This directory is a blank Nx workspace, and will have the plugin's built package installed locally.

means that you can then go to `tmp/nx-e2e/proj` and use it as you need, running nx commands, editing files, trying things.
So my tests are `nx e2e nx-plugin-openapi-e2e`, followed by some tinkering in the tmp project just in case.

**Comment by djbreen7** [comment]
@trumbitta Thanks! That second part especially helps.

**Comment by trumbitta** [comment]
Also, @all-contributors please add @djbreen7 for his code and bug contributions

**Pull request merged**
